#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_PIM
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PIM")]
	public partial class PIMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttabCarteira(tabCarteira instance);
    partial void UpdatetabCarteira(tabCarteira instance);
    partial void DeletetabCarteira(tabCarteira instance);
    partial void InserttabMoedas(tabMoedas instance);
    partial void UpdatetabMoedas(tabMoedas instance);
    partial void DeletetabMoedas(tabMoedas instance);
    partial void InserttabUser(tabUser instance);
    partial void UpdatetabUser(tabUser instance);
    partial void DeletetabUser(tabUser instance);
    #endregion
		
		public PIMDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PIMConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PIMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PIMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PIMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PIMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tabCarteira> tabCarteira
		{
			get
			{
				return this.GetTable<tabCarteira>();
			}
		}
		
		public System.Data.Linq.Table<tabMoedas> tabMoedas
		{
			get
			{
				return this.GetTable<tabMoedas>();
			}
		}
		
		public System.Data.Linq.Table<tabUser> tabUser
		{
			get
			{
				return this.GetTable<tabUser>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tabCarteira")]
	public partial class tabCarteira : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCarteira;
		
		private string _endCarteira;
		
		private System.Nullable<float> _saldoCarteira;
		
		private int _idUser;
		
		private int _idTipoRegis;
		
		private EntityRef<tabMoedas> _tabMoedas;
		
		private EntityRef<tabUser> _tabUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCarteiraChanging(int value);
    partial void OnidCarteiraChanged();
    partial void OnendCarteiraChanging(string value);
    partial void OnendCarteiraChanged();
    partial void OnsaldoCarteiraChanging(System.Nullable<float> value);
    partial void OnsaldoCarteiraChanged();
    partial void OnidUserChanging(int value);
    partial void OnidUserChanged();
    partial void OnidTipoRegisChanging(int value);
    partial void OnidTipoRegisChanged();
    #endregion
		
		public tabCarteira()
		{
			this._tabMoedas = default(EntityRef<tabMoedas>);
			this._tabUser = default(EntityRef<tabUser>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCarteira", DbType="Int NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idCarteira
		{
			get
			{
				return this._idCarteira;
			}
			set
			{
				if ((this._idCarteira != value))
				{
					this.OnidCarteiraChanging(value);
					this.SendPropertyChanging();
					this._idCarteira = value;
					this.SendPropertyChanged("idCarteira");
					this.OnidCarteiraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endCarteira", DbType="VarChar(100)")]
		public string endCarteira
		{
			get
			{
				return this._endCarteira;
			}
			set
			{
				if ((this._endCarteira != value))
				{
					this.OnendCarteiraChanging(value);
					this.SendPropertyChanging();
					this._endCarteira = value;
					this.SendPropertyChanged("endCarteira");
					this.OnendCarteiraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldoCarteira", DbType="Float")]
		public System.Nullable<float> saldoCarteira
		{
			get
			{
				return this._saldoCarteira;
			}
			set
			{
				if ((this._saldoCarteira != value))
				{
					this.OnsaldoCarteiraChanging(value);
					this.SendPropertyChanging();
					this._saldoCarteira = value;
					this.SendPropertyChanged("saldoCarteira");
					this.OnsaldoCarteiraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUser", DbType="Int NOT NULL")]
		public int idUser
		{
			get
			{
				return this._idUser;
			}
			set
			{
				if ((this._idUser != value))
				{
					if (this._tabUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidUserChanging(value);
					this.SendPropertyChanging();
					this._idUser = value;
					this.SendPropertyChanged("idUser");
					this.OnidUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoRegis", DbType="Int NOT NULL")]
		public int idTipoRegis
		{
			get
			{
				return this._idTipoRegis;
			}
			set
			{
				if ((this._idTipoRegis != value))
				{
					if (this._tabMoedas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTipoRegisChanging(value);
					this.SendPropertyChanging();
					this._idTipoRegis = value;
					this.SendPropertyChanged("idTipoRegis");
					this.OnidTipoRegisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tabMoedas_tabCarteira", Storage="_tabMoedas", ThisKey="idTipoRegis", OtherKey="idTipoRegis", IsForeignKey=true)]
		public tabMoedas tabMoedas
		{
			get
			{
				return this._tabMoedas.Entity;
			}
			set
			{
				tabMoedas previousValue = this._tabMoedas.Entity;
				if (((previousValue != value) 
							|| (this._tabMoedas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tabMoedas.Entity = null;
						previousValue.tabCarteira.Remove(this);
					}
					this._tabMoedas.Entity = value;
					if ((value != null))
					{
						value.tabCarteira.Add(this);
						this._idTipoRegis = value.idTipoRegis;
					}
					else
					{
						this._idTipoRegis = default(int);
					}
					this.SendPropertyChanged("tabMoedas");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tabUser_tabCarteira", Storage="_tabUser", ThisKey="idUser", OtherKey="idUser", IsForeignKey=true)]
		public tabUser tabUser
		{
			get
			{
				return this._tabUser.Entity;
			}
			set
			{
				tabUser previousValue = this._tabUser.Entity;
				if (((previousValue != value) 
							|| (this._tabUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tabUser.Entity = null;
						previousValue.tabCarteira.Remove(this);
					}
					this._tabUser.Entity = value;
					if ((value != null))
					{
						value.tabCarteira.Add(this);
						this._idUser = value.idUser;
					}
					else
					{
						this._idUser = default(int);
					}
					this.SendPropertyChanged("tabUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tabMoedas")]
	public partial class tabMoedas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTipoRegis;
		
		private string _nomTipo;
		
		private float _quantMoeda;
		
		private EntitySet<tabCarteira> _tabCarteira;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTipoRegisChanging(int value);
    partial void OnidTipoRegisChanged();
    partial void OnnomTipoChanging(string value);
    partial void OnnomTipoChanged();
    partial void OncotMoedaChanging(float value);
    partial void OncotMoedaChanged();
    #endregion
		
		public tabMoedas()
		{
			this._tabCarteira = new EntitySet<tabCarteira>(new Action<tabCarteira>(this.attach_tabCarteira), new Action<tabCarteira>(this.detach_tabCarteira));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoRegis", DbType="Int NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTipoRegis
		{
			get
			{
				return this._idTipoRegis;
			}
			set
			{
				if ((this._idTipoRegis != value))
				{
					this.OnidTipoRegisChanging(value);
					this.SendPropertyChanging();
					this._idTipoRegis = value;
					this.SendPropertyChanged("idTipoRegis");
					this.OnidTipoRegisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomTipo", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string nomTipo
		{
			get
			{
				return this._nomTipo;
			}
			set
			{
				if ((this._nomTipo != value))
				{
					this.OnnomTipoChanging(value);
					this.SendPropertyChanging();
					this._nomTipo = value;
					this.SendPropertyChanged("nomTipo");
					this.OnnomTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantMoeda", DbType="Float NOT NULL")]
		public float cotMoeda
		{
			get
			{
				return this._quantMoeda;
			}
			set
			{
				if ((this._quantMoeda != value))
				{
					this.OncotMoedaChanging(value);
					this.SendPropertyChanging();
					this._quantMoeda = value;
					this.SendPropertyChanged("cotMoeda");
					this.OncotMoedaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tabMoedas_tabCarteira", Storage="_tabCarteira", ThisKey="idTipoRegis", OtherKey="idTipoRegis")]
		public EntitySet<tabCarteira> tabCarteira
		{
			get
			{
				return this._tabCarteira;
			}
			set
			{
				this._tabCarteira.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tabCarteira(tabCarteira entity)
		{
			this.SendPropertyChanging();
			entity.tabMoedas = this;
		}
		
		private void detach_tabCarteira(tabCarteira entity)
		{
			this.SendPropertyChanging();
			entity.tabMoedas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tabUser")]
	public partial class tabUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idUser;
		
		private string _nomUser;
		
		private string _senhaUser;
		
		private string _telUser;
		
		private string _cpfUser;
		
		private System.DateTime _dataUser;
		
		private string _emailUser;
		
		private EntitySet<tabCarteira> _tabCarteira;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUserChanging(int value);
    partial void OnidUserChanged();
    partial void OnnomUserChanging(string value);
    partial void OnnomUserChanged();
    partial void OnsenhaUserChanging(string value);
    partial void OnsenhaUserChanged();
    partial void OntelUserChanging(string value);
    partial void OntelUserChanged();
    partial void OncpfUserChanging(string value);
    partial void OncpfUserChanged();
    partial void OndataUserChanging(System.DateTime value);
    partial void OndataUserChanged();
    partial void OnemailUserChanging(string value);
    partial void OnemailUserChanged();
    #endregion
		
		public tabUser()
		{
			this._tabCarteira = new EntitySet<tabCarteira>(new Action<tabCarteira>(this.attach_tabCarteira), new Action<tabCarteira>(this.detach_tabCarteira));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUser", DbType="Int NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idUser
		{
			get
			{
				return this._idUser;
			}
			set
			{
				if ((this._idUser != value))
				{
					this.OnidUserChanging(value);
					this.SendPropertyChanging();
					this._idUser = value;
					this.SendPropertyChanged("idUser");
					this.OnidUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomUser", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nomUser
		{
			get
			{
				return this._nomUser;
			}
			set
			{
				if ((this._nomUser != value))
				{
					this.OnnomUserChanging(value);
					this.SendPropertyChanging();
					this._nomUser = value;
					this.SendPropertyChanged("nomUser");
					this.OnnomUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senhaUser", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string senhaUser
		{
			get
			{
				return this._senhaUser;
			}
			set
			{
				if ((this._senhaUser != value))
				{
					this.OnsenhaUserChanging(value);
					this.SendPropertyChanging();
					this._senhaUser = value;
					this.SendPropertyChanged("senhaUser");
					this.OnsenhaUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telUser", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string telUser
		{
			get
			{
				return this._telUser;
			}
			set
			{
				if ((this._telUser != value))
				{
					this.OntelUserChanging(value);
					this.SendPropertyChanging();
					this._telUser = value;
					this.SendPropertyChanged("telUser");
					this.OntelUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpfUser", DbType="VarChar(14) NOT NULL", CanBeNull=false)]
		public string cpfUser
		{
			get
			{
				return this._cpfUser;
			}
			set
			{
				if ((this._cpfUser != value))
				{
					this.OncpfUserChanging(value);
					this.SendPropertyChanging();
					this._cpfUser = value;
					this.SendPropertyChanged("cpfUser");
					this.OncpfUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataUser", DbType="Date NOT NULL")]
		public System.DateTime dataUser
		{
			get
			{
				return this._dataUser;
			}
			set
			{
				if ((this._dataUser != value))
				{
					this.OndataUserChanging(value);
					this.SendPropertyChanging();
					this._dataUser = value;
					this.SendPropertyChanged("dataUser");
					this.OndataUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailUser", DbType="VarChar(70)")]
		public string emailUser
		{
			get
			{
				return this._emailUser;
			}
			set
			{
				if ((this._emailUser != value))
				{
					this.OnemailUserChanging(value);
					this.SendPropertyChanging();
					this._emailUser = value;
					this.SendPropertyChanged("emailUser");
					this.OnemailUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tabUser_tabCarteira", Storage="_tabCarteira", ThisKey="idUser", OtherKey="idUser")]
		public EntitySet<tabCarteira> tabCarteira
		{
			get
			{
				return this._tabCarteira;
			}
			set
			{
				this._tabCarteira.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tabCarteira(tabCarteira entity)
		{
			this.SendPropertyChanging();
			entity.tabUser = this;
		}
		
		private void detach_tabCarteira(tabCarteira entity)
		{
			this.SendPropertyChanging();
			entity.tabUser = null;
		}
	}
}
#pragma warning restore 1591
