<?xml version="1.0" encoding="utf-8"?><Database Name="PIM" Class="PIMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=PIM;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PIMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tabCarteira" Member="tabCarteira">
    <Type Name="tabCarteira">
      <Column Name="idCarteira" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="endCarteira" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="saldoCarteira" Type="System.Single" DbType="Float" CanBeNull="true" />
      <Column Name="idUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idTipoRegis" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tabMoedas_tabCarteira" Member="tabMoedas" ThisKey="idTipoRegis" OtherKey="idTipoRegis" Type="tabMoedas" IsForeignKey="true" />
      <Association Name="tabUser_tabCarteira" Member="tabUser" ThisKey="idUser" OtherKey="idUser" Type="tabUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tabMoedas" Member="tabMoedas">
    <Type Name="tabMoedas">
      <Column Name="idTipoRegis" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nomTipo" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="cotMoeda" Storage="_quantMoeda" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="tabMoedas_tabCarteira" Member="tabCarteira" ThisKey="idTipoRegis" OtherKey="idTipoRegis" Type="tabCarteira" />
    </Type>
  </Table>
  <Table Name="dbo.tabUser" Member="tabUser">
    <Type Name="tabUser">
      <Column Name="idUser" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nomUser" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="senhaUser" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="telUser" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="cpfUser" Type="System.String" DbType="VarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="dataUser" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="emailUser" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Association Name="tabUser_tabCarteira" Member="tabCarteira" ThisKey="idUser" OtherKey="idUser" Type="tabCarteira" />
    </Type>
  </Table>
</Database>